application:
  port: 8080
database:
  host: 127.0.0.1
  port: 3306
  name: digitizer
  username: root
  password: root
folder:
  dropbox: D:\Works\GO\src\github.com\syahriarreza\alfresco-doc-digitizer\.ignored\pdf\dropbox
  scan: D:\Works\GO\src\github.com\syahriarreza\alfresco-doc-digitizer\.ignored\pdf\scan
  process: D:\Works\GO\src\github.com\syahriarreza\alfresco-doc-digitizer\.ignored\pdf\process
  upload: D:\Works\GO\src\github.com\syahriarreza\alfresco-doc-digitizer\.ignored\pdf\upload
scheduler:
  every_x_minute: 5
  poolsize: 20
alfresco:
  default_path: CompanyHome/Guest Home